version: '3.1'

services:

  postgres:
    image: postgres:latest
    ports: 
      - 5432:5432
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres