CREATE TABLE IF NOT EXISTS GameSession (
  GameSession_Id SERIAL PRIMARY KEY NOT NULL,
  Game_State CHARACTER VARYING,
  Player_Count INTEGER
);

CREATE TABLE IF NOT EXISTS Player (
  Player_Id SERIAL PRIMARY KEY NOT NULL,
  Player_Name CHARACTER VARYING(12),
  Player_Status CHARACTER VARYING,
  Player_Role CHARACTER VARYING,
  GameSession_Id SERIAL REFERENCES GameSession
);