CREATE TABLE IF NOT EXISTS GameSession (
  GameSessionId SERIAL PRIMARY KEY NOT NULL
);

CREATE TABLE IF NOT EXISTS Player (
  PlayerId SERIAL PRIMARY KEY NOT NULL,
  PlayerName CHARACTER VARYING(12),
  GameSessionId SERIAL REFERENCES GameSession(GameSessionId)
);
